# Generated by Django 3.2.5 on 2021-07-13 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('savensharebase', '0002_auto_20210713_1822'),
    ]

    operations = [
        migrations.RenameField(
            model_name='linkfile',
            old_name='title',
            new_name='filetitle',
        ),
    ]
