# Generated by Django 3.2.5 on 2021-07-25 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('savensharebase', '0003_rename_title_linkfile_filetitle'),
    ]

    operations = [
        migrations.RenameField(
            model_name='linkfile',
            old_name='file',
            new_name='uploadfile',
        ),
    ]
