# Generated by Django 3.2.5 on 2021-07-25 07:34

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('savensharebase', '0004_rename_file_linkfile_uploadfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linkfile',
            name='filetitle',
            field=models.CharField(max_length=200, verbose_name='Set File Title'),
        ),
        migrations.CreateModel(
            name='LinkWritePost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posttitle', models.CharField(max_length=200, verbose_name='Set Post Title')),
                ('description', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
