# Generated by Django 3.2.5 on 2021-07-26 05:14

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('savensharebase', '0005_auto_20210725_1334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linkwritepost',
            name='description',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
