# Generated by Django 3.2.5 on 2021-07-26 05:35

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('savensharebase', '0006_alter_linkwritepost_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linkwritepost',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
    ]
